add cookie consent banner and functionality for it
storj/Tardigrade.io pull request #22
Opened 2019-05-01 21:16 UTC by fuskovic

This PR does the following 
- adds a cookie consent banner
- script adds cookie to user browser on load
- script checks for cookie and does not display banner if cookie is already present

2019-05-01 21:16 UTC, fuskovic commented
Pending staging approval

2019-05-02 13:33 UTC, fuskovic commented
changed script to only add cookie on banner close per Andi

2019-05-02 13:52 UTC, VinozzZ requested changes
Left some comments

2019-05-02 13:55 UTC, fuskovic commented on layouts/partials/site-scripts.html
> +        currentTab.style.borderLeft = "2px solid #2582FF";
onClick for the use-cases partial. It's not related to this PR I just moved it into site-scripts to refactor it some.

2019-05-02 13:56 UTC, fuskovic commented on layouts/partials/site-scripts.html
> +    function select(e){
onClick for the use-cases partial. It's not related to this PR I just moved it into site-scripts to refactor it some.

2019-05-02 13:56 UTC, fuskovic commented on assets/scss/_base.scss
> +.consent-banner{
the banner goes on the whole site.

2019-05-02 14:07 UTC, VinozzZ commented on assets/scss/_base.scss
> +.consent-banner{
Yes, I meant that the rules are global in _base.scss in terms o f elements. It's for rules that will affect native HTML elements across the whole site. Maybe I'm not explaining it well. Check this article https://matthewelsom.com/blog/simple-scss-playbook.html#base. 
To me, the `.consent-banner` is a component specific rule. it only affects the banner no matter where the banner is used. It doesn't affect other parts of the page. Does that make sense?

2019-05-02 14:17 UTC, fuskovic commented on layouts/partials/site-scripts.html
> +            choices[i].style.borderLeft = "2px solid #DCDCDC";
this does not work using classes the way it should due to bootstrap specificity issues - even when you add !important. Also, this is functionality that we decided to take out anyway in the near future with Atikh and is also unrelated to the PR so I will leave it as is until we remove it entirely in the next sprint or two. This is for the use-cases image changing onclick when I did the vanguard update on the homepage.

2019-05-02 14:17 UTC, fuskovic commented on layouts/partials/site-scripts.html
> +        currentTab.style.borderLeft = "2px solid #2582FF";
this does not work using classes the way it should due to bootstrap specificity issues - even when you add !important. Also, this is functionality that we decided to take out anyway in the near future with Atikh and is also unrelated to the PR so I will leave it as is until we remove it entirely in the next sprint or two. This is for the use-cases image changing onclick when I did the vanguard update on the homepage.

2019-05-02 14:34 UTC, fuskovic commented on assets/scss/_base.scss
> +.consent-banner{
It just seems weird to make an entirely new SCSS file for one element. The consent banner is actually applied in the footer partial. By that logic, I should be adding the rules in the _footer.scss file right ?

2019-05-02 15:04 UTC, fuskovic commented on assets/scss/_base.scss
> +.consent-banner{
Ok I made a new file for this.

2019-05-02 15:05 UTC, fuskovic commented on assets/scss/_base.scss
> +    font-family: "Roboto";
done

2019-05-02 15:05 UTC, fuskovic commented on layouts/partials/consentBanner.html
> +        <p class="consent-banner_text">This site uses cookies. By continuing to use this site you are agreeing to our <a class="consent-banner_text" style="text-decoration:underline;" href="https://s
done

2019-05-02 15:09 UTC, VinozzZ approved these changes

2019-05-02 15:09 UTC, merged